### ISSUE TITLE
./configure is missing from libdockapp 0.6.4

### ISSUE THREAD

**Issue by SanskritFritz** [d-torrance/dockapps#3]
How do I compile it?

**Comment by d-torrance** [comment]
autoreconf -fvi

That will generate the configure script.  Thanks for pointing this out -- I'll make sure to update the README for the next release.

**Comment by SanskritFritz** [comment]
Woa, thanks for the quick answer. My next humble question is, where is now the official home for libdockapps? My guess is http://windowmaker.org/dockapps/?name=libdockapp

**Comment by d-torrance** [comment]
No problem!  You're correct -- that's the official home.

**Comment by SanskritFritz** [comment]
Thanks for your help. I'm the maintainer of the archlinux package, it works now like charm.
