### ISSUE TITLE
how can i install or build a binary from this repo

### ISSUE THREAD

**Issue by gity-up** [d-torrance/dockapps#4]
i'm specifically interested in installing wmwlmon. i run manjaro and there is no package in the pacman or aur sources. i'm lost on how to use any of the files in the wmwlmon folder to build. can you assist or point me in the right direction?

thanks

**Comment by d-torrance** [comment]
It _should_ just be a simple `make`.

However, it looks like the code for wmwlmon has been untouched for 8 years, and the build fails using modern tools.

I'll take a look and see if we can get it working again.  :)

**Comment by gity-up** [comment]
yeah :disappointed: i downloaded the zip file from the author's site (http://www.nazgul.ch/dev_wmwlmon.html) and it failed during make.

thanks for your reply & offerring to get it working again :fearful: :scream: :open_mouth: :smiley: . either way, your the bomb :boom: .

**Comment by d-torrance** [comment]
Apologies for the very delayed reply.  I took a look at wmwlmon, and it looks like it was written specifically for FreeBSD and OpenBSD.

Are you using one of the BSDs or Linux?

**Comment by gity-up** [comment]
no, :disappointed: i am not using free or open bsd. no worries though. i have moved on :smiley: .

i'll close this now. thank you very much, you're appreciated.
