### ISSUE TITLE
Do not include pathnames in Window Name and Class Properties -- apply basename to argv[0] for wname

### ISSUE THREAD

**Issue by Corin-EU** [d-torrance/dockapps#5]
In libdockapps file wmgeneral.c, wname is set from argv[0] and is then used to set the window name and class resource.  Often applications are called with their full path which then means that the window name has a path in it, thereby requiring an unwieldy path specific string for "Name"  in WMState if the applet is to be captured in the WM dock.

The simple solution is that wname should be the basename of argv[0] to ensure that the window name for the applet is the simple and obvious one. Thus the inclusion of header file libgen.h is required.

[wmgeneral.c.patch.txt](https://github.com/d-torrance/dockapps/files/959469/wmgeneral.c.patch.txt)

This change also needs to be applied to applets using their own (and ancient) copy of wmgeneral, eg wmSMPmon, wmSun, wmmisc, wmtop, wmtz, wmweather.

Just say "no" to path slashes "/" in window name/class resources ....

**Comment by d-torrance** [comment]
Thanks for the patch!  I've submitted it to the official dockapps repository [1].

I haven't applied it to wmsmpmon, wsun, etc. yet.  Eventually, I'd like to migrate those over to libdockapp anyway.

[1] http://repo.or.cz/dockapps.git/commit/fa7743b
